"""Build Deckster's small, auditable CC0 starter sound pack.

The three downloaded inputs are hash-pinned. The Kenney archive is never
extracted; only explicitly named audio members are decoded. The other
sounds are deterministic synthesis generated by this script.

Usage:
    python tools/build_default_sound_pack.py \
        --kenney-zip release/default-sounds-sources/kenney_interface-sounds.zip \
        --crickets-wav release/default-sounds-sources/cricketsounds090613.wav \
        --applause-wav release/default-sounds-sources/applause-clapping-church-crowd-immersive.wav
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import math
import wave
import zipfile
from pathlib import Path

import numpy as np
import soundfile as sf


RATE = 48_000
KENNEY_SHA256 = "f2193d072726d6758a5f7871b2dcc54dcce0d5c35c6f0a62f92549b327c81232"
CRICKETS_SHA256 = "ecc088a3d1ab967202b63a92836dadc47bd08c8ab3f17d8527f620264aa5faf9"
APPLAUSE_SHA256 = "0d3bfde5a050f3c5e6685bd7f1efc7ab1d289fbad65c88c1ce9b4691228c69c9"
KENNEY_FILES = {
    "success.wav": "Audio/confirmation_001.ogg",
    "wrong.wav": "Audio/error_006.ogg",
    "record-scratch.wav": "Audio/scratch_004.ogg",
    "pop.wav": "Audio/pluck_001.ogg",
}


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _resample(samples: np.ndarray, source_rate: int) -> np.ndarray:
    samples = np.asarray(samples, dtype=np.float32)
    if samples.ndim == 2:
        samples = samples.mean(axis=1)
    if source_rate == RATE:
        return samples
    length = max(1, round(len(samples) * RATE / source_rate))
    return np.interp(
        np.linspace(0, len(samples) - 1, length),
        np.arange(len(samples)), samples,
    ).astype(np.float32)


def _finish(samples: np.ndarray, peak: float = 0.86, fade_ms: int = 12) -> np.ndarray:
    samples = np.nan_to_num(np.asarray(samples, dtype=np.float32))
    highest = float(np.max(np.abs(samples))) if len(samples) else 0.0
    if highest:
        samples = samples * (peak / highest)
    fade = min(len(samples) // 2, round(RATE * fade_ms / 1000))
    if fade:
        ramp = np.linspace(0.0, 1.0, fade, dtype=np.float32)
        samples[:fade] *= ramp
        samples[-fade:] *= ramp[::-1]
    return np.clip(samples, -1.0, 1.0)


def _write_wav(path: Path, samples: np.ndarray, fade_ms: int = 12) -> None:
    pcm = (_finish(samples, fade_ms=fade_ms) * 32767).astype("<i2")
    with wave.open(str(path), "wb") as out:
        out.setnchannels(1)
        out.setsampwidth(2)
        out.setframerate(RATE)
        out.writeframes(pcm.tobytes())


def _tone(freq: float | np.ndarray, seconds: float, phase: float = 0.0) -> np.ndarray:
    count = round(seconds * RATE)
    if np.isscalar(freq):
        return np.sin(2 * math.pi * float(freq) * np.arange(count) / RATE + phase).astype(np.float32)
    freq = np.asarray(freq, dtype=np.float32)[:count]
    return np.sin(2 * math.pi * np.cumsum(freq) / RATE + phase).astype(np.float32)


def _burst(rng: np.random.Generator, seconds: float, decay: float = 20.0) -> np.ndarray:
    count = round(seconds * RATE)
    time = np.arange(count) / RATE
    noise = rng.normal(0, 1, count).astype(np.float32)
    # A simple high-pass turns white noise into a sharper clap/snare texture.
    noise[1:] -= 0.82 * noise[:-1]
    return noise * np.exp(-decay * time)


def _air_horn() -> np.ndarray:
    seconds = 1.05
    count = round(seconds * RATE)
    time = np.arange(count) / RATE
    # Lower fundamentals give the horn body; upper partials keep it audible on phones.
    vibrato = 1.0 + .004 * np.sin(2 * math.pi * 5.5 * time)
    sound = sum(
        (1 / harmonic ** .78) * np.sin(2 * math.pi * base * harmonic * vibrato * time)
        for base in (164.81, 220.0, 277.18) for harmonic in range(1, 7)
    )
    sound += .28 * np.sin(2 * math.pi * 82.4 * time)
    envelope = np.minimum(1.0, time / .012) * np.minimum(1.0, (seconds - time) / .12)
    return (sound * envelope).astype(np.float32)


def _rimshot(rng: np.random.Generator) -> np.ndarray:
    seconds = .72
    count = round(seconds * RATE)
    sound = np.zeros(count, dtype=np.float32)
    kick = _tone(np.linspace(135, 62, round(.24 * RATE)), .24) * np.exp(-18 * np.arange(round(.24 * RATE)) / RATE)
    sound[:len(kick)] += kick * .75
    snare_at = round(.29 * RATE)
    snare = _burst(rng, .22, 24)
    sound[snare_at:snare_at + len(snare)] += snare * .55
    stick_at = round(.49 * RATE)
    stick = _tone(1720, .06) * np.exp(-70 * np.arange(round(.06 * RATE)) / RATE)
    sound[stick_at:stick_at + len(stick)] += stick
    return sound


def _sad_trombone() -> np.ndarray:
    # Preserve the recognizable descending semitones from pack v2.
    notes = (233.08, 220.0, 207.65, 196.0)
    parts = []
    for index, note in enumerate(notes):
        seconds = .43 if index < 3 else .72
        count = round(seconds * RATE)
        time = np.arange(count) / RATE
        pitch = note * (1 + .006 * np.sin(2 * math.pi * 5 * time))
        if index == 3:
            pitch *= 1 - .07 * np.maximum(0, (time - .35) / (seconds - .35))
        phase = 2 * math.pi * np.cumsum(pitch) / RATE
        brass = (np.sin(phase) + .38 * np.sin(2 * phase)
                 + .18 * np.sin(3 * phase) + .09 * np.sin(4 * phase))
        envelope = np.minimum(1, time / .012) * np.minimum(1, (seconds - time) / .065)
        parts.append((brass * envelope).astype(np.float32))
    return np.concatenate(parts)


def _drum_roll(rng: np.random.Generator) -> np.ndarray:
    seconds = 1.72
    sound = np.zeros(round(seconds * RATE), dtype=np.float32)
    times = np.linspace(0, 1, 22) ** 1.28 * 1.32
    for index, at in enumerate(times):
        burst = _burst(rng, .075, 43)
        body = _tone(np.linspace(190, 115, len(burst)), .075)
        burst = .72 * burst + .42 * body * np.exp(-38 * np.arange(len(body)) / RATE)
        start = round(at * RATE)
        sound[start:start + len(burst)] += burst * (.28 + .025 * index)
    crash = _burst(rng, .34, 12)
    start = round(1.36 * RATE)
    take = min(len(crash), len(sound) - start)
    sound[start:start + take] += crash[:take] * .78
    return _presence(sound, 3.0)


def _bell() -> np.ndarray:
    """Bright struck bell with a strong first hit and audible midrange ring."""
    seconds = 1.25
    time = np.arange(round(seconds * RATE)) / RATE
    partials = ((880, 1.0, 3.8), (1320, .55, 4.6), (1760, .34, 6.0),
                (2218, .26, 8.0), (2640, .16, 9.0))
    ring = sum(weight * np.sin(2 * math.pi * freq * time) * np.exp(-decay * time)
               for freq, weight, decay in partials)
    strike = .22 * np.sin(2 * math.pi * 3400 * time) * np.exp(-95 * time)
    return ((ring + strike) * np.minimum(1, time / .002)).astype(np.float32)


def _fanfare() -> np.ndarray:
    sound = np.zeros(round(1.05 * RATE), dtype=np.float32)
    for at, freq, duration in ((0, 392, .17), (.20, 523.25, .17),
                               (.40, 659.25, .42)):
        time = np.arange(round(duration * RATE)) / RATE
        phase = 2 * math.pi * freq * time
        horn = np.sin(phase) + .5 * np.sin(2 * phase) + .25 * np.sin(3 * phase)
        env = np.minimum(1, time / .008) * np.minimum(1, (duration - time) / .045)
        start = round(at * RATE)
        sound[start:start + len(horn)] += (horn * env).astype(np.float32)
    return sound


def _impact(rng: np.random.Generator) -> np.ndarray:
    seconds = .7
    time = np.arange(round(seconds * RATE)) / RATE
    pitch = 135 * np.exp(-time * 8) + 45
    thump = np.sin(2 * math.pi * np.cumsum(pitch) / RATE) * np.exp(-time * 10)
    crack = _burst(rng, seconds, 42)
    return (.95 * thump + .55 * crack).astype(np.float32)


def _laser() -> np.ndarray:
    seconds = .48
    time = np.arange(round(seconds * RATE)) / RATE
    pitch = 1650 * np.exp(-time * 8) + 180
    phase = 2 * math.pi * np.cumsum(pitch) / RATE
    envelope = np.exp(-time * 7) * np.minimum(1, time / .003)
    return ((np.sin(phase) + .38 * np.sin(2 * phase)) * envelope).astype(np.float32)


def _boing() -> np.ndarray:
    seconds = .68
    time = np.arange(round(seconds * RATE)) / RATE
    pitch = 220 + 150 * np.exp(-time * 8) * np.cos(2 * math.pi * 11 * time)
    phase = 2 * math.pi * np.cumsum(pitch) / RATE
    envelope = np.exp(-time * 5.5) * np.minimum(1, time / .004)
    return ((np.sin(phase) + .35 * np.sin(2 * phase)) * envelope).astype(np.float32)


def _presence(samples: np.ndarray, drive: float = 6.0) -> np.ndarray:
    """Raise quiet crowd/field detail without letting rare peaks set the whole level."""
    return (np.tanh(np.asarray(samples, dtype=np.float32) * drive)
            / np.tanh(drive)).astype(np.float32)


def _censor_bleep() -> np.ndarray:
    seconds = 1.05
    count = round(seconds * RATE)
    time = np.arange(count) / RATE
    gate = (np.sin(2 * math.pi * 8 * time) > -.85).astype(np.float32)
    envelope = np.minimum(1, time / .01) * np.minimum(1, (seconds - time) / .04)
    return (_tone(1000, seconds) * gate * envelope).astype(np.float32)


def _build(kenney_zip: Path, crickets_wav: Path, applause_wav: Path, output: Path) -> None:
    if _sha256(kenney_zip) != KENNEY_SHA256:
        raise SystemExit("Kenney archive hash does not match the reviewed source")
    if _sha256(crickets_wav) != CRICKETS_SHA256:
        raise SystemExit("Crickets WAV hash does not match the reviewed source")
    if _sha256(applause_wav) != APPLAUSE_SHA256:
        raise SystemExit("Applause WAV hash does not match the reviewed source")

    output.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(kenney_zip) as archive:
        names = set(archive.namelist())
        missing = set(KENNEY_FILES.values()) - names
        if missing:
            raise SystemExit(f"Kenney archive is missing reviewed entries: {sorted(missing)}")
        for destination, member in KENNEY_FILES.items():
            with archive.open(member) as source:
                samples, rate = sf.read(io.BytesIO(source.read()), always_2d=True, dtype="float32")
            _write_wav(output / destination, _resample(samples, rate))

    crickets, rate = sf.read(crickets_wav, always_2d=True, dtype="float32")
    crickets = _resample(crickets, rate)
    excerpt_start = 19 * RATE
    _write_wav(output / "crickets.wav",
               _presence(crickets[excerpt_start:excerpt_start + round(1.6 * RATE)], 5.0))

    applause, rate = sf.read(applause_wav, always_2d=True, dtype="float32")
    applause = _resample(applause, rate)
    # Tight section of the real crowd recording, with the claps raised above the hall wash.
    _write_wav(output / "applause.wav",
               _presence(applause[round(5.7 * RATE):round(8.5 * RATE)], 7.0))

    rng = np.random.default_rng(0xDEC057E2)
    generated = {
        "air-horn.wav": _air_horn(),
        "rimshot.wav": _rimshot(rng),
        "sad-trombone.wav": _sad_trombone(),
        "drum-roll.wav": _drum_roll(rng),
        "censor-bleep.wav": _censor_bleep(),
        "bell.wav": _bell(),
        "fanfare.wav": _fanfare(),
        "impact.wav": _impact(rng),
        "laser.wav": _laser(),
        "boing.wav": _boing(),
    }
    for filename, samples in generated.items():
        _write_wav(output / filename, samples,
                   fade_ms=2 if filename in {"bell.wav", "impact.wav"} else 12)

    clips = [
        ("crickets", "crickets.wav", "Crickets", "🦗", .82),
        ("rimshot", "rimshot.wav", "Rimshot", "🥁", .82),
        ("applause", "applause.wav", "Applause", "👏", .9),
        ("air-horn", "air-horn.wav", "Air horn", "📣", .68),
        ("sad-trombone", "sad-trombone.wav", "Sad trombone", "🎺", .78),
        ("record-scratch", "record-scratch.wav", "Record scratch", "💿", .82),
        ("drum-roll", "drum-roll.wav", "Drum roll", "🥁", .78),
        ("censor-bleep", "censor-bleep.wav", "Censor bleep", "🤐", .55),
        ("success", "success.wav", "Success", "✅", .95),
        ("wrong", "wrong.wav", "Wrong answer", "❌", .9),
        ("bell", "bell.wav", "Bell", "🔔", .9),
        ("pop", "pop.wav", "Pop", "🫧", .95),
        ("fanfare", "fanfare.wav", "Fanfare", "🎉", .8),
        ("impact", "impact.wav", "Impact", "💥", .78),
        ("laser", "laser.wav", "Laser", "🔫", .75),
        ("boing", "boing.wav", "Boing", "🌀", .8),
    ]
    manifest = {
        "version": 4,
        "license": "CC0-1.0",
        "clips": [
            {
                "key": key, "file": filename, "label": label, "emoji": emoji,
                "voice": True, "ears": True, "gain": gain,
                "sha256": _sha256(output / filename),
            }
            for key, filename, label, emoji, gain in clips
        ],
    }
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    sums = [f"{clip['sha256']}  {clip['file']}" for clip in manifest["clips"]]
    (output / "SHA256SUMS").write_text("\n".join(sums) + "\n", encoding="ascii")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kenney-zip", required=True, type=Path)
    parser.add_argument("--crickets-wav", required=True, type=Path)
    parser.add_argument("--applause-wav", required=True, type=Path)
    parser.add_argument("--output", type=Path, default=Path("assets/default-sounds"))
    args = parser.parse_args()
    _build(args.kenney_zip.resolve(), args.crickets_wav.resolve(),
           args.applause_wav.resolve(), args.output.resolve())


if __name__ == "__main__":
    main()
